name: nginx-sample

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Check and fetch repo
        run: echo "Repo checked out!"

      - name: Build image
      - run: |
        cd example-project
        docker build . -t my-nginx:latest

  run:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Run Docker container
        run: |
          docker run --name nginx-service -p 80:80 -d my-nginx:latest
