name: nginx-sample

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Check and fetch repo
        run: echo "Repo checked out!"

      - name: Build image
        run: |
          docker build ./example-project -t my-nginx:latest

  run:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Kill all (hard policy)
        run: docker ps -q | grep -q . && docker kill $(docker ps -q) || echo "Nothing to kill"
      - name: Run Docker container
        run: |
          docker run -d -p 80:80 my-nginx:latest
